### ISSUE TITLE
Refine GENESYS File

### ISSUE THREAD

**Issue by lydia-wu** [lydia-wu/cadence#10]
**Purpose**: to refine the team's GENESYS file and develop imaging for DGs
supports: #8  #7 
tasking due date: `Monday 2021-10-04 @10AM EDT`

tasking:
- [x] conditionally format Requirements to visually link **StRS** and **SRS**
  - [x] consider assigning 1 color per client **SRS** and 1 color for all the academic requirements
  - [x] consider assigning corresponding colors to **StRS** (example: say stakeholder req `R.1.1` is _red_.  If system req `R.3.3.3.1` maps to stakeholder req `R.1.1`, then `R.3.3.3.1` adopts `R.1.1`'s color, in this case, _red_)
  - [x] create a key of the **StRS** colors in the `.xslx` file in a separate sheet
  - [x] take a picture of a key of the **StRS** colors so that it can later be added to the **SRS** image, and drop it in this issue (try to take a snapshot that doesn't have gridlines or typos, but also that is small enough to put in the corner of a hierarchy diagram)
- [x] import all corrected **StRS** `numbers`/`names`/`descriptions`/`originators`/`any other information in the excel` to GENESYS
  - [x] try to find a GENESYS field that corresponds with `originators`.  Consider `owner`, `lead`, `point of contact (POC)` or something along those lines; comment below on what you've decided
  - [x] consider double-checking that all **SRS** values are still congruent with the `.xlsx` file
- [x] zip the GENESYS file and upload to here;  @lydia-wu will work on manually rearranging objects for the snapshot of the hierarchy diagrams

Post questions in this `issue` as you discover them.

**Comment by hunter-alloway** [comment]
Below are the modifications I have made to the GENESYS file as well as the shared Excel document:
1. I mapped all of the system requirements back to the mission statement (Since each stakeholder requirement is mapped back to the Mission Statement, the system requirements should also be as they are influenced by the stakeholder requiremens) We can link add additional documentation and discuss this topic in later meetings?

2. I have gone through and filled out the rest of the description fields in Excel to ensure both a description and rationale exist for each system requirement

3. In order to map the originators column to the system requirement, the "notes" element will be used to identify additional information regarding a requirement i.e. not only will the "notes" element be used in order to link the originators column, but any additional information outside of the fields in the GENESYS system requirements elements can be found in the "notes" field regarding a requirement. 

The relationship "has comments" will be used in the system requirements in GENESYS to precipitate (connect the requirement to) the originators field, found in the "originators" subfolder. (see attached screenshot)

Finally, typos and other gramatical errors were updated. I will attach the updated GENESYS file to this thread shortly.


![Originator](https://user-images.githubusercontent.com/90055695/135488484-48463166-9cc0-4fa2-a320-fc8292c06aba.PNG)

**Comment by hunter-alloway** [comment]
The corresponding linked system and stakeholder requirements were also updated in Excel

**Comment by hunter-alloway** [comment]
The "originator" field has now been updated in Excel and shall define the originators for each system requirement. The originators will be located under the "Note" element and is related to the system requirements through relationship: "has comments". (see image attached)

@lydia-wu for your convenience, I have temporarily removed the ralationship: "refined by" for the "System Requirements" field as this will make it easier for you to format the hierarchy design for both the "Build a set of Tools" and "Combine Metric Data" requirement fields. (see screenshot attached)

Please feel free to contact me on Discord for any questions/concerns :)


![Comments On-Originator Field](https://user-images.githubusercontent.com/90055695/135667823-91c81ab1-ea05-4836-bd93-1b8879772d3e.PNG)
![Lydia-GENESYS](https://user-images.githubusercontent.com/90055695/135667824-d2769381-8bbf-42b3-8ca2-a458ce9c72aa.PNG)

**Comment by hunter-alloway** [comment]
Conditional formatting updated and posted on the shared Excel doc. Please let me know if you want me to change anything...it looks much better when you open it on desktop. This is just a rough draft, so please critique the document and give me any feedback you may have. I will be happy to modify the formatting accordingly. Have a great weekend :)

**Comment by hunter-alloway** [comment]
Stakeholder and system requirements have been mapped using conditional formatting based on cell values. A key cannot be created as the system requirements are too large to be categorized.  A potential alternative would be to create a table or chart aligning system to staekeholder requirements.

**Comment by lydia-wu** [comment]
here's an updated .gnux that has some `numbering (R.#.# etc)`/`refined by`/`refined` corrections

[ENGR481_Team03_Internet_of_Things.zip](https://github.com/lydia-wu/cadence/files/7279193/ENGR481_Team03_Internet_of_Things.zip)
:
