### ISSUE TITLE
Operation 1: Data Generator

### ISSUE THREAD

**Issue by lydia-wu** [lydia-wu/cadence#30]
Step 1:
Create `python` code that outputs an array with `2 columns`: `DeviceID`, `DeviceStatus`, `Timestamp`.

`DeviceStatus` has three options: `strongConnection`, `weakConnection`, `noConnection`
`DeviceID` has two options: `10001`, `12345`

Assign the `DeviceStatus` at random to either `DeviceID`

Output: `csv file` local to computer that captures the outputs

### To Write to CSV
https://www.pythontutorial.net/python-basics/python-write-csv-file/
```python
import csv 

header = ['DeviceID', 'DeviceStatus', 'Timestamp']
data = [
             ['10001', 'strongConnection', timestamp(2021-07-03 16:21:12.357246)],
             ['12345', 'strongConnection', timestamp(2021-07-03 16:22:13.246)],
             ['12345', 'weakConnection', timestamp(2021-07-03 19:22:13.246)],
             ['12345', 'strongConnection', timestamp(2021-07-03 19:45:13.246)],
             ['12345', 'strongConnection', timestamp(2021-07-03 20:22:13.246)],
             ['10001', 'noConnection', timestamp(2021-07-03 23:21:12.357246)]
            ]

with open('HuntersData.csv', 'w', encoding='UTF8') as f:
    writer = csv.writer(f)

    # write the header
    writer.writerow(header)

    # write the data
    writer.writerow(data)

```

### To get python timestamp
https://pynative.com/python-timestamp/

### To write a thread for python to execute every minute or so

**Comment by lydia-wu** [comment]
@hunter-alloway 

First round:
10 minutes of data
"Hello World" 10 times should show up in Michael's ingestion point, one for each minute

**Comment by hunter-alloway** [comment]
@lydia-wu @htyuki @michaeld3951 
Following a lengthy discussion/working session with Mr. Stansell, we have created the simulation data environment 1 that will generate CSV files: 

- That run with real time 
- Delay the time between sending information regarding the transmission/recepotion of CSV files from the log device
- The simulation counts 10 times, writes a file, waits, writes a second file, waits, writes a third file, waits again and counts the delays for each time stamp and writes a "narrative" that is visible in the CSV file 
- Constructed a while loop in order to run each Device, App, and Network program 
- The "count" increments each "Hello World" while running for the 10-minute lifespan of the program ]
- The device, Network, and Cloud Application tell a story of the connection, disconnection, timestamp and contents of the devices behavior

Attached are the three CSV files that were generated using Version 1 of the Data Simulator and the narrative template.
These files are also uploaded in "<>Code-->CSV's" in GitHub
The third file is a template of the narrative that will follow the execution of the simulator and illustrates the communication between all aspects of the simulation environment.

[AppReport.csv](https://github.com/lydia-wu/cadence/files/7998914/AppReport.csv)
[DeviceLog.log](https://github.com/lydia-wu/cadence/files/7998915/DeviceLog.log)
[NetworkReport.csv](https://github.com/lydia-wu/cadence/files/7998916/NetworkReport.csv)
[Cadence-Parent Simulator Tagline.txt](https://github.com/lydia-wu/cadence/files/7998917/Cadence-Parent.Simulator.Tagline.txt)

**Comment by lydia-wu** [comment]
Shifting gears; well done
