### ISSUE TITLE
Set Open-Source Toolset: Environments and Software

### ISSUE THREAD

**Issue by lydia-wu** [lydia-wu/cadence#34]
`2022-01-26 W 12 PM`

To Establish for team:
- [ ] Visual Studio Code Setup / Preferences
- [x] GitHub Repo Connection

**Comment by lydia-wu** [comment]
@htyuki @michaeld3951 @hunter-alloway 

Good news: I think I understand how to sync up our local copies of code with this repo. When we meet 1-on-1 tomorrow, we'll be following these instructions in this order to link `GitHub` with `VS Code`:

(1) https://zeroesandones.medium.com/how-to-create-a-repository-on-github-and-clone-it-locally-using-vscode-91543517a455
(2) http://vcloud-lab.com/entries/powershell/solved-visual-studio-code-make-sure-you-configure-your-user-name-and-user-email-in-git
(3) https://zeroesandones.medium.com/how-to-commit-and-push-your-changes-to-your-github-repository-in-vscode-77a7a3d7dd02

For @hunter-alloway: we'll make sure Python is up to snuff

For @michaeld3951: make sure ELK is already running on your computer, and we'll practice committing a file/process to GitHub; have a file already ready to commit

For @htyuki: make sure ELK and PowerBI are both already running on your computer, and we'll run through committing both to GitHub

**Comment by hunter-alloway** [comment]
Tips that may prove to be helpful to you guys as I have been learning to work with VS code and the git extension in order to publish code straight from my hard drive.
[Committing my First Changes-Cadence Data Simulator.docx](https://github.com/lydia-wu/cadence/files/7921582/Committing.my.First.Changes-Cadence.Data.Simulator.docx)
